---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: custom-ubuntu
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        # tail -f /dev/null
        command: ["tail"]
        args:
        - "-f"
        - "/dev/null"
        livenessProbe:
          exec:
            command:
            - echo
            - "Hello world!"
          initialDelaySeconds: 5
          periodSeconds: 30