# Diviser les secrets dans un autre fichier afin de pouvoir les déplacer dans un autre Git
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque # Pour définir des clés comme un ConfigMap
data:
  mysql_root_password: MTExMTExMTEK # echo -n "11111111" | base64