# # TODO: Appliquer le fichier de configuration ci-dessous pour créer un ServiceAccount et un ClusterRoleBinding
# # spec.jobTemplate.spec.template.spec.serviceAccountName: cronjob-sa

# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: cronjob-sa # TODO: attribuer au CronJob
#   namespace: default
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: ingress-reader-cluster
# rules:
#   - apiGroups: ["networking.k8s.io"]
#     resources: ["ingresses"]
#     verbs: ["get", "list"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: ingress-reader-cluster-binding
# subjects:
#   - kind: ServiceAccount
#     name: cronjob-sa
#     namespace: default
# roleRef:
#   kind: ClusterRole
#   name: ingress-reader-cluster
#   apiGroup: rbac.authorization.k8s.io
