# TODO: Appliquer le fichier de configuration ci-dessous pour créer un ServiceAccount et un ClusterRoleBinding
# spec.jobTemplate.spec.template.spec.serviceAccountName: serviceaccount-cronjob
# Permet au CronJob de faire la commande : kubectl get ingresses

apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount-cronjob
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrole-cronjob
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrolebinding-cronjob
subjects:
  - kind: ServiceAccount
    name: serviceaccount-cronjob
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-role-cronjob
  apiGroup: rbac.authorization.k8s.io