services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 12345:8080
    environment:
      - MY_VAR_1=COMPOSE # écrase le ENV du Dockerfile
    command: tail -f /dev/null # écrase le CMD du Dockerfile